<template>
    <div id="app"
         v-on:mousemove="onMouseMove" 
         v-on:mouseup="onMouseUp" 
         v-on:mousedown="onMouseDown" 
         v-on:dblclick="onMouseDoubleClick"
         >
        <Obl v-for="obl in obls" :key="obl.id"
            v-bind:initialRadius="obl.radius" 
            v-bind:left="obl.left" 
            v-bind:top="obl.top"
            v-bind:label="obl.label"
            v-bind:id="obl.id"
            v-bind:dblClickCallback="onMouseDoubleClick"
            />
        </div>
  </div>
</template>

<script>
import Obl from './components/Obl.vue'

export default {
    name: 'app',
    data() {
        return {
            isCanvasSelected: false,
            origin: {
                x: 0,
                y: 0
            },
            obls: [ 
                { id: 1, radius: 100, left: 10, top: 10, label: "small" },
                { id: 2, radius: 200, left: 100, top: 100, label: "medium" },
                { id: 3, radius: 300, left: 200, top: 200, label: "ellipse" },
            ],
            isRemoveEnabled: false,
        }
    },
    methods: {
        getChildren: function(id) {
            return [
                { id: 4, radius: 100, left: 100, top: 100, label: 'four'},
                { id: 5, radius: 100, left: 300, top: 300, label: 'five'},
                { id: 6, radius: 100, left: 500, top: 500, label: 'six'},
            ];
        },
        onMouseDoubleClick: function(event) {
            for(let obl of this.$children) {
                if(obl.isOver(event.pageX, event.pageY)) {
                    this.obls = this.getChildren(obl.id);
                    return;
                }
            }
            this.obls.push({
                radius: 200,
                left: event.pageX - 200,
                top: event.pageY - 200,
                label: 'New Obl',
                // TODO: replace this random id with one generated by the server.
                // This should be the result of a POST request.
                id: Math.floor(Math.random() * 10000) + 100,
            });
        },
        onMouseUp: function(event) {
            for(let obl of this.$children) {
                obl.isDragging = false;
            }
            this.isCanvasSelected = false;
        },
        onMouseMove: function(event) {
            if(this.isCanvasSelected) {
                this.origin.x += event.movementX;
                this.origin.y += event.movementY;
                for(let obl of this.$children) {
                    obl.originX = this.origin.x;
                    obl.originY = this.origin.y;
                }
            } else {
                for(let obl of this.$children) {
                    if(!obl.isDragging) continue;
                    obl.onMouseMove(event);
                }
            }
        },
        onMouseDown: function(event) {
            let isOblSelected = false;
            for(let obl of this.$children) {
                if(obl.isOver(event.pageX, event.pageY)) {
                    obl.isDragging = true;
                    isOblSelected = true;
                    obl.select();
                } else {
                    obl.deselect();
                }
            }
            if(isOblSelected) {
                this.isRemoveEnabled = true;
                return;
            }
            this.isCanvasSelected = true;
            this.isRemoveEnabled = false;
        },
        onRemoveMouseDown: function(event) {
            let oblsToRemove = []
            for(let obl of this.$children) {
                if(!obl.isActive) continue;
                let model = this.obls.find(o => o.id == obl.id);
                if(model == null) continue;
                oblsToRemove.push(model);
            }

            if(oblsToRemove.length == 0) return;
            this.obls = this.obls.filter(o => !oblsToRemove.includes(o));
        },
    },
    components: {
        Obl 
    }
}
</script>

<style>
body {
    background: black;
}
#app {
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  z-index: -1;
  overflow-x: hidden;
  overflow-y: hidden;
}
.toolbar-button {
    opacity: 1;
}
</style>
