<template>
  <div id="app" 
       v-on:mousemove="onMouseMove" 
       v-on:mouseup="onMouseUp" 
       v-on:mousedown="onMouseDown" 
       v-on:dblclick="onMouseDoubleClick"
       >
    <Obl v-for="obl in obls" 
        v-bind:initialRadius="obl.radius" 
        v-bind:left="obl.left" 
        v-bind:top="obl.top"
        v-bind:label="obl.label"
        v-bind:id="obl.id"
        />
    <div id="toolbar">
        <div>
            <svg v-on:mousedown="onRemoveMouseDown" v-if="isRemoveEnabled" width="64" height="64" xmlns="http://www.w3.org/2000/svg">
             <!-- Created with Method Draw - http://github.com/duopixel/Method-Draw/ -->
             <g>
              <title>background</title>
              <rect fill="none" id="canvas_background" height="66" width="66" y="-1" x="-1"/>
              <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid">
               <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%"/>
              </g>
             </g>
             <g>
              <title>Layer 1</title>
              <ellipse stroke="#ff0000" ry="30" rx="30" id="svg_4" cy="32.322763" cx="32.374996" stroke-width="1.5" fill="#ff0000"/>
              <text transform="rotate(-45 31.35941314697265,31.88277626037597) " xml:space="preserve" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="101" id="svg_5" y="67.041834" x="1.875129" stroke-width="0" stroke="#ff0000" fill="#ffffff">+</text>
             </g>
            </svg>
            <svg v-if="!isRemoveEnabled" width="64" height="64" xmlns="http://www.w3.org/2000/svg">
             <!-- Created with Method Draw - http://github.com/duopixel/Method-Draw/ -->
             <g>
              <title>background</title>
              <rect fill="none" id="canvas_background" height="66" width="66" y="-1" x="-1"/>
              <g display="none" overflow="visible" y="0" x="0" height="100%" width="100%" id="canvasGrid">
               <rect fill="url(#gridpattern)" stroke-width="0" y="0" x="0" height="100%" width="100%"/>
              </g>
             </g>
             <g>
              <title>Layer 1</title>
              <ellipse stroke="#b2b2b2" ry="30" rx="30" id="svg_4" cy="32.322763" cx="32.374996" stroke-width="1.5" fill="#b2b2b2"/>
              <text style="cursor: move;" transform="rotate(-45 31.359374999999993,31.882812500000004) " xml:space="preserve" text-anchor="start" font-family="Helvetica, Arial, sans-serif" font-size="101" id="svg_5" y="67.041834" x="1.875129" stroke-width="0" stroke="#ff0000" fill="#ffffff">+</text>
             </g>
            </svg>
        </div>
    </div>
  </div>
</template>

<script>
import Obl from './components/Obl.vue'

export default {
    name: 'app',
    data() {
        return {
            isCanvasSelected: false,
            origin: {
                x: 0,
                y: 0
            },
            obls: [ 
                { id: 1, radius: 100, left: 10, top: 10, label: "small" },
                { id: 2, radius: 200, left: 100, top: 100, label: "medium" },
                { id: 3, radius: 300, left: 200, top: 200, label: "ellipse" },
            ],
            isRemoveEnabled: false,
        }
    },
    methods: {
        onMouseDoubleClick: function(event) {
            for(let obl of this.$children) {
                if(obl.isOver(event.pageX, event.pageY)) return;
            }
            this.obls.push({
                radius: 200,
                left: event.pageX - 200,
                top: event.pageY - 200,
                label: 'New Obl',
                // TODO: replace this random id with one generated by the server.
                // This should be the result of a POST request.
                id: Math.floor(Math.random() * 10000) + 100,
            });
        },
        onMouseUp: function(event) {
            for(let obl of this.$children) {
                obl.isDragging = false;
            }
            this.isCanvasSelected = false;
        },
        onMouseMove: function(event) {
            if(this.isCanvasSelected) {
                this.origin.x += event.movementX;
                this.origin.y += event.movementY;
                for(let obl of this.$children) {
                    obl.originX = this.origin.x;
                    obl.originY = this.origin.y;
                }
            } else {
                for(let obl of this.$children) {
                    if(!obl.isDragging) continue;
                    obl.onMouseMove(event);
                }
            }
        },
        onMouseDown: function(event) {
            let isOblSelected = false;
            for(let obl of this.$children) {
                if(obl.isOver(event.pageX, event.pageY)) {
                    obl.isDragging = true;
                    isOblSelected = true;
                    obl.select();
                } else {
                    obl.deselect();
                }
            }
            if(isOblSelected) {
                this.isRemoveEnabled = true;
                return;
            }
            this.isCanvasSelected = true;
            this.isRemoveEnabled = false;
        },
        onRemoveMouseDown: function(event) {
            for(let obl of this.$children) {
                if(!obl.isActive) continue;
                let model = this.obls.filter(o => o.id == obl.id);
                this.obls.splice(this.obls.indexOf(model, 0), 1);
            }
        },
    },
    components: {
        Obl 
    }
}
</script>

<style>
body {
    background: black;
}
#app {
  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  z-index: -1;
  overflow-x: hidden;
  overflow-y: hidden;
}
#toolbar {
    position: absolute;
    right: 0px;
    top: 0px;
    bottom: 0px;
    width: 70px;
    background: white;
    opacity: 0.5;
}
</style>
